var drinks = {
    "UTC-13": {drink: "Yeastie boys", country: "Nuova Zelanda", flag: "13.png"},
    "UTC-12": {drink: "Stocazzo", country: "St. Marteen", flag: null},
    "UTC-11": {drink: "Vino francese", country: "Nuova Caledonia", flag: "11.png"},
    "UTC-10": {drink: "Birra Coopers", country: "Australia", flag: "10.png"},
    "UTC-9": {drink: "Sakè", country: "Giappone", flag: "9.png"},
    "UTC-8": {drink: "Mei Kui Lu", country: "Cina", flag: "8.png"},
    "UTC-7": {drink: "Birra Singha", country: "Thailandia", flag: "7.png"},
    "UTC-6": {drink: "Vodka", country: "Kazahstan", flag: "6.png"},
    "UTC-5": {drink: "Birra Cobra", country: "India", flag: "5.png"},
    "UTC-4": {drink: "Rum", country: "Mauritius", flag: "4.png"},
    "UTC-3": {drink: "Birra analcolica", country: "Arabia Saudita", flag: "3.png"},
    "UTC-2": {drink: "Ouzo", country: "Grecia", flag: "2.png"},
    "UTC-1": {drink: "Prosecco", country: "Italia", flag: "1.png"},
    "UTC_0": {drink: "Sangrìa", country: "Canarie", flag: "0.png"},
    "UTC_1": {drink: "Porto", country: "Azzorre", flag: "_1.png"},
    "UTC_2": {drink: "Gin", country: "South Georgia", flag: "_2.png"},
    "UTC_3": {drink: "Fernet", country: "Argentina", flag: "_3.png"},
    "UTC_4": {drink: "Stocazzo", country: "St. Marteen", flag: null},
}